export const ADD_PR0DUCT = 'ADD_PR0DUCT'
export const ADD_PR0DUCT_SUCCESS = 'ADD_PR0DUCT_SUCCES'
export const ADD_PR0DUCT_ERROR = 'ADD_PR0DUCT_ERROR'

export const START_DOWNLOAD_PRODUCTS = 'START_DOWNLOAD_PRODUCTS'
export const START_DOWNLOAD_SUCCESS = 'START_DOWNLOAD_SUCCESS'
export const START_DOWNLOAD_ERROR = 'START_DOWNLOAD_ERROR'

export const GET_DELETE_PRODUCT = 'GET_DELETE_PRODUCT'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'

export const GET_EDIT_PRODUCT = 'GET_EDIT_PRODUCT'
export const START_EDIT_PRODUCT = 'START_EDIT_PRODUCT'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDDEN_ALERT = 'HIDDEN_ALERT'