export const USER_AUTHENTICATED =  'USER_AUTHENTICATED'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const RESET_ALERT = 'RESET_ALERT'
export const SHOW_ALERT = 'SHOW_ALERT'

export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUCCESS= 'LOGIN_SUCCESS'

export const LOGOUT= 'LOGOUT'

export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const UPLOAD_FILE_FAILED = 'UPLOAD_FILE_FAILED'

export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS'
export const CREATE_LINK_FAILED = 'CREATE_LINK_FAILED'

export const UPLOAD_FILE = 'UPLOAD_FILE'

export const RESET_STATE = 'RESET_STATE'

export const ADD_PASSWORD = 'ADD_PASSWORD'


export const ADD_MAX_DOWNLOADS= 'ADD_MAX_DOWNLOADS'